server:
  port: 8761
  servlet:
    context-path: /
spring:
  application:
    name: lwj-erueka
  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
      peerEurekaNodesUpdateIntervalMs: 60000
      enableSelfPreservation: true
  client:
#  表示是否将自己注册到server
    register-with-eureka: false
#    是否从server上获取注册信息，默认为true,单点的server不需要从别的server获取
    fetch-registry: false
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:123456@localhost:8761/eureka/